### ISSUE TITLE
More OS/Processor Support

### ISSUE THREAD

**Issue by starsoccer** [wozz/ha-addons#48]
It seems like currently only aarch64 is supported, but when trying to install on my machine I am being told "This add-on is not compatible with the processor of your device or the operating system you have installed on your device."
```
OS Family | Linux
Operating System Version | 6.6.33-haos
CPU Architecture | x86_64
```

**Comment by wozz** [comment]
which one are you trying to run?

**Comment by starsoccer** [comment]
Whoops totally forgot to include it. I was trying to run `Logspout `

**Comment by wozz** [comment]
added https://github.com/wozz/ha-addons/commit/07fe9e8311ffacb3bdc83f134722eda68f518b10

**Comment by starsoccer** [comment]
Awesome, can confirm it works now
